services:
  db:
    image: postgres:13
    container_name: workshop-db
    environment:
      DATABASE_URL: "postgres://workshops_user:oc2024@db:5432/workshopsdb"
      POSTGRES_USER: workshops_user
      POSTGRES_PASSWORD: oc2024
      POSTGRES_DB: workshopsdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshops_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: workshop-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/workshopsdb"
      SPRING_DATASOURCE_USERNAME: workshops_user
      SPRING_DATASOURCE_PASSWORD: oc2024
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
